### ISSUE TITLE
Listen store specific item

### ISSUE THREAD

**Issue by joeybronner** [Spyna/react-store#22]
Hey, 

Is it possible to subscribre on specific item changes in the store ?
The method "listener: (state) => {}" doesn't fit with my need... I want to subscribe from sub components... 

Thank you in advance for your support man

**Comment by Spyna** [comment]
Hi, 
I'm happy to fulfill your request, however, I'm not sure to have fully understood it. What do you mean with sub-components? 
Could you please give an example of how you would use the code? 
Eg: `<MyComponent listenTo={store.myProperty} />` or whatever you were thinking about..

Thank you

**Comment by MarianBe** [comment]
@Spyna i think something like this would be nice to have:
`
const config = {
  listener: state => {
    if (this.props.courses !== state.courses) {
      // Do something
    }
  }
}
const ConnectedHome = withStore(Home, ['courses'], config)
`

**Comment by MarianBe** [comment]
you're right, totally forgot about componentDidUpdate!
